# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#

service: api
# app and org for use with dashboard.serverless.com
app: api-server
org: venkatsuresh

provider:
  name: aws
  runtime: nodejs16.x
  logs:
    restApi: true

plugins:
  - serverless-domain-manager

custom:
  cognitoConfig: ${file(./config/config.json)}
  customDomain:
    domainName: api.momentcapturer.com
    certificateName: 'api.momentcapturer.com'
    stage: ${opt:stage, self:provider.stage, 'dev'}
    createRoute53Record: true
    # endpointType: "regional"

functions:
  csr:
    handler: csr.process
    memorySize: 1536
    timeout: 10
    events:
      - http:
          path: csr
          method: post
          cors: true
          authorizer:
            name: CognitoAuthorizer
            arn: arn:aws:cognito-idp:${self:custom.cognitoConfig.COGNITO_REGION}:${self:custom.cognitoConfig.COGNITO_ACCOUNT_ID}:userpool/${self:custom.cognitoConfig.COGNITO_USERPOOL_ID}
            identitySource: method.request.header.Authorization
            type: COGNITO_USER_POOLS
  getData:
    handler: dynamo.getData
    events:
      - http:
          path: getData
          method: get
          cors: true
  getBestImagePerCategory:
    handler: dynamo.getBestImagePerCategory
    events:
      - http:
          path: getBestImagePerCategory
          method: get
          cors: true
  editImageMetadata:
    handler: editImage.process
    events:
      - http:
          path: editImageMetadata
          method: post
          cors: true
          authorizer:
            name: CognitoAuthorizer
            arn: arn:aws:cognito-idp:${self:custom.cognitoConfig.COGNITO_REGION}:${self:custom.cognitoConfig.COGNITO_ACCOUNT_ID}:userpool/${self:custom.cognitoConfig.COGNITO_USERPOOL_ID}
            identitySource: method.request.header.Authorization
            type: COGNITO_USER_POOLS
  deleteImage:
    handler: deleteImage.process
    events:
      - http:
          path: deleteImage
          method: post
          cors: true
          authorizer:
            name: CognitoAuthorizer
            arn: arn:aws:cognito-idp:${self:custom.cognitoConfig.COGNITO_REGION}:${self:custom.cognitoConfig.COGNITO_ACCOUNT_ID}:userpool/${self:custom.cognitoConfig.COGNITO_USERPOOL_ID}
            identitySource: method.request.header.Authorization
            type: COGNITO_USER_POOLS
